export enum ReturnReason {
  WRONG_ITEM = "WRONG_ITEM",
  DEFECTIVE = "DEFECTIVE",
  NOT_AS_DESCRIBED = "NOT_AS_DESCRIBED",
  CHANGED_MIND = "CHANGED_MIND",
  RECEIVED_AS_GIFT = "RECEIVED_AS_GIFT",
  DUPLICATE_ORDER = "DUPLICATE_ORDER",
  LATE_DELIVERY = "LATE_DELIVERY",
  DAMAGED_IN_SHIPPING = "DAMAGED_IN_SHIPPING",
  OTHER = "OTHER",
}
