export enum InventoryReferenceType {
  ORDER = "ORDER",
  PURCHASE_ORDER = "PURCHASE_ORDER",
  STORE_ADJUSTMENT = "STORE_ADJUSTMENT",
  ORDER_RETURN = "ORDER_RETURN",
  TRANSFER = "TRANSFER",
  MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT",
  INITIAL = "INITIAL",
  INVENTORY_ADJUSTMENT = "INVENTORY_ADJUSTMENT",
}
